#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListviewAnimations.Sample.Resource", IsApplication=true)]

namespace ListviewAnimations.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.components.stickylistheaders.Resource.String.ApplicationName = global::ListviewAnimations.Sample.Resource.String.ApplicationName;
			global::com.refractored.components.stickylistheaders.Resource.String.Hello = global::ListviewAnimations.Sample.Resource.String.Hello;
			global::ListviewAnimations.Core.Resource.String.ApplicationName = global::ListviewAnimations.Sample.Resource.String.ApplicationName;
			global::ListviewAnimations.Core.Resource.String.Hello = global::ListviewAnimations.Sample.Resource.String.Hello;
			global::ListviewAnimations.Manipulation.Resource.String.ApplicationName = global::ListviewAnimations.Sample.Resource.String.ApplicationName;
			global::ListviewAnimations.Manipulation.Resource.String.Hello = global::ListviewAnimations.Sample.Resource.String.Hello;
			global::ListViewAnimations.SLH.Resource.String.ApplicationName = global::ListviewAnimations.Sample.Resource.String.ApplicationName;
			global::ListViewAnimations.SLH.Resource.String.Hello = global::ListviewAnimations.Sample.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int appearance_examples = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int swipedismiss = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int bg_actionbar = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int blue_transparent = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int green_transparent = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int holo_red_light_transparent = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int pink_transparent = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int purple_transparent = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int red_transparent = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int paddingTop = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_dropdown = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card_background_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_beer = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_github = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_undo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int img_main_appearance = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int img_main_googlecards = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int img_main_gridview = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int img_main_itemmanipulation = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int img_main_stickylistheaders = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int img_manipulation_animateaddition = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int img_manipulation_expand = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int img_manipulation_swipetodismiss = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int img_nature1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int img_nature2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int img_nature3 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int img_nature4 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int img_nature5 = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000a
			public const int Appearance = 2131361802;
			
			// aapt resource value: 0x7f0a0001
			public const int DynamicListView = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int ExpandList = 2131361794;
			
			// aapt resource value: 0x7f0a000b
			public const int GridViewExample = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public const int ItemManipulation = 2131361801;
			
			// aapt resource value: 0x7f0a000c
			public const int ListViewSLH = 2131361804;
			
			// aapt resource value: 0x7f0a0000
			public const int activity_dynamiclistview_listview = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int activity_expandablelistitem_card_content = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int activity_expandablelistitem_card_title = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int activity_googlecards_card_imageview = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int activity_googlecards_card_textview = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int activity_googlecards_listview = 2131361797;
			
			// aapt resource value: 0x7f0a0008
			public const int activity_gridview_gv = 2131361800;
			
			// aapt resource value: 0x7f0a000d
			public const int activity_mylist_listview = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int activity_stickylistheaders_listview = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int list_row_draganddrop_textview = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int list_row_draganddrop_touchview = 2131361808;
			
			// aapt resource value: 0x7f0a0013
			public const int menu_expandable_limit = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int menu_main_beer = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int menu_main_beer2 = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int menu_main_beer3 = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int menu_main_beer4 = 2131361816;
			
			// aapt resource value: 0x7f0a0014
			public const int menu_main_donate = 2131361812;
			
			// aapt resource value: 0x7f0a0019
			public const int menu_main_github = 2131361817;
			
			// aapt resource value: 0x7f0a0011
			public const int undo_row_texttv = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int undo_row_undobutton = 2131361810;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_dynamiclistview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_dynamiclistview_header = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_examples_itemmanipulations = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_expandablelistitem_card = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_googlecards = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_googlecards_card = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_gridview = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_mylist = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_stickylistheaders = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int list_header = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int list_row = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int list_row_draganddrop = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int list_row_dynamiclistview = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int undo_row = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu_expandablelistitem = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int menu_main = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040021
			public const int activity_dynamiclistview_header = 2130968609;
			
			// aapt resource value: 0x7f040012
			public const int animateaddition = 2130968594;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000b
			public const int appearance = 2130968587;
			
			// aapt resource value: 0x7f04001a
			public const int card_number = 2130968602;
			
			// aapt resource value: 0x7f040010
			public const int draganddrop = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int dynamiclistview = 2130968593;
			
			// aapt resource value: 0x7f04001c
			public const int exception = 2130968604;
			
			// aapt resource value: 0x7f040013
			public const int expandablelistitemadapter = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int expandorcollapsecard = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int explainexpand = 2130968598;
			
			// aapt resource value: 0x7f040009
			public const int googlecards = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int gridview = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int gridviewexample = 2130968591;
			
			// aapt resource value: 0x7f040019
			public const int header = 2130968601;
			
			// aapt resource value: 0x7f040014
			public const int itemdeleted = 2130968596;
			
			// aapt resource value: 0x7f04000e
			public const int itemmanipulation = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int limit = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int menu_beer = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int menu_beer2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int menu_beer3 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int menu_beer4 = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int menu_donate = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int menu_github = 2130968584;
			
			// aapt resource value: 0x7f04001d
			public const int moved = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int newly_added_item = 2130968608;
			
			// aapt resource value: 0x7f04001e
			public const int removed_positions = 2130968606;
			
			// aapt resource value: 0x7f040018
			public const int row_number = 2130968600;
			
			// aapt resource value: 0x7f04000c
			public const int stickylistheaders = 2130968588;
			
			// aapt resource value: 0x7f04001f
			public const int tap_to_insert = 2130968607;
			
			// aapt resource value: 0x7f040015
			public const int taptoundo = 2130968597;
			
			// aapt resource value: 0x7f04001b
			public const int thanks = 2130968603;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int AppTheme_ActionBar = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int AppTheme_ActionBar_TitleTextStyle = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int DropDownNav_Example = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
